data_source:
  path: "data"
dataset:
  name: "IEMOCAP"
dataset_specific:
  IEMOCAP:
    preprocessed:
      dir: "Preprocessed"
      file: "audio_and_text.csv"
    sessions: 1
dataloader:
  batch_size: 16
  shuffle: true
train:
  experiment_id: 1
