data_source:
  path: "data"
dataset:
  name: "IEMOCAP"
dataset_specific:
  IEMOCAP:
    preprocessed:
      dir: "Preprocessed"
      file: "audio_and_text.csv"
    emotions: ["ang", "fru", "neu", "sur", "sad", "exc", "hap", "fea", "dis", "oth"]
dataloader:
  batch_size: 1
  shuffle: true
  num_workers: 12
models:
  pretrained_alexnet: "https://download.pytorch.org/models/alexnet-owt-4df8aa71.pth"
  save_location: "saved_models"
